/**
 * ICPC Vietnam - real scoreboard data, generated by scripts/scrape-icpcvn.mjs;
 * do not edit the JSON files by hand.
 * - National 2021–2025
 * - Regional (ICPC Asia, Vietnam host) 2021–2025
 * - Regional high-school division (HSGS) 2022/2024/2025
 * - Asia Pacific Championship (APAC) 2024–2026
 * Banned/practice teams (negative score marker) are excluded at scrape time.
 */
import type { ContestProblem, Team } from '@/lib/api/schemas'
import problemsApac2024 from './problems-apac-2024.json'
import problemsApac2025 from './problems-apac-2025.json'
import problemsApac2026 from './problems-apac-2026.json'
import problems2021 from './problems-2021.json'
import problems2022 from './problems-2022.json'
import problems2023 from './problems-2023.json'
import problems2024 from './problems-2024.json'
import problems2025 from './problems-2025.json'
import problemsRegional2021 from './problems-regional-2021.json'
import problemsRegional2022 from './problems-regional-2022.json'
import problemsRegional2023 from './problems-regional-2023.json'
import problemsRegional2024 from './problems-regional-2024.json'
import problemsRegional2025 from './problems-regional-2025.json'
import problemsRegionalHs2022 from './problems-regional-hsgs-2022.json'
import problemsRegionalHs2024 from './problems-regional-hsgs-2024.json'
import problemsRegionalHs2025 from './problems-regional-hsgs-2025.json'
import teamsApac2024 from './teams-apac-2024.json'
import teamsApac2025 from './teams-apac-2025.json'
import teamsApac2026 from './teams-apac-2026.json'
import teams2021 from './teams-2021.json'
import teams2022 from './teams-2022.json'
import teams2023 from './teams-2023.json'
import teams2024 from './teams-2024.json'
import teams2025 from './teams-2025.json'
import teamsRegional2021 from './teams-regional-2021.json'
import teamsRegional2022 from './teams-regional-2022.json'
import teamsRegional2023 from './teams-regional-2023.json'
import teamsRegional2024 from './teams-regional-2024.json'
import teamsRegional2025 from './teams-regional-2025.json'
import teamsRegionalHs2022 from './teams-regional-hsgs-2022.json'
import teamsRegionalHs2024 from './teams-regional-hsgs-2024.json'
import teamsRegionalHs2025 from './teams-regional-hsgs-2025.json'

export { icpcVnOrganizations, rawOrgNameMap } from './orgs'

export const icpcVnTeams: Team[] = [
  ...(teams2021 as Team[]),
  ...(teams2022 as Team[]),
  ...(teams2023 as Team[]),
  ...(teams2024 as Team[]),
  ...(teams2025 as Team[]),
]

export const icpcVnProblems: Record<number, ContestProblem[]> = {
  2021: problems2021 as ContestProblem[],
  2022: problems2022 as ContestProblem[],
  2023: problems2023 as ContestProblem[],
  2024: problems2024 as ContestProblem[],
  2025: problems2025 as ContestProblem[],
}

export const icpcRegionalTeams: Team[] = [
  ...(teamsRegional2021 as Team[]),
  ...(teamsRegional2022 as Team[]),
  ...(teamsRegional2023 as Team[]),
  ...(teamsRegional2024 as Team[]),
  ...(teamsRegional2025 as Team[]),
]

export const icpcRegionalProblems: Record<number, ContestProblem[]> = {
  2021: problemsRegional2021 as ContestProblem[],
  2022: problemsRegional2022 as ContestProblem[],
  2023: problemsRegional2023 as ContestProblem[],
  2024: problemsRegional2024 as ContestProblem[],
  2025: problemsRegional2025 as ContestProblem[],
}

export const icpcRegionalHsTeams: Team[] = [
  ...(teamsRegionalHs2022 as Team[]),
  ...(teamsRegionalHs2024 as Team[]),
  ...(teamsRegionalHs2025 as Team[]),
]

export const icpcRegionalHsProblems: Record<number, ContestProblem[]> = {
  2022: problemsRegionalHs2022 as ContestProblem[],
  2024: problemsRegionalHs2024 as ContestProblem[],
  2025: problemsRegionalHs2025 as ContestProblem[],
}

export const icpcApacTeams: Team[] = [
  ...(teamsApac2024 as Team[]),
  ...(teamsApac2025 as Team[]),
  ...(teamsApac2026 as Team[]),
]

export const icpcApacProblems: Record<number, ContestProblem[]> = {
  2024: problemsApac2024 as ContestProblem[],
  2025: problemsApac2025 as ContestProblem[],
  2026: problemsApac2026 as ContestProblem[],
}
